<!DOCTYPE html>
<?php 
$con=mysqli_connect("localhost","root","","myhmsdb");

include('newfunc.php');

// --- 1. PDF GENERATION LOGIC (Keep this for archiving) ---
function generate_patient_history($pid){
  $con=mysqli_connect("localhost","root","","myhmsdb");
  $pat_query = mysqli_query($con, "SELECT * FROM patreg WHERE pid='$pid'");
  $pat_row = mysqli_fetch_array($pat_query);
  $app_query = mysqli_query($con, "SELECT * FROM appointmenttb WHERE pid='$pid'");
  $pres_query = mysqli_query($con, "SELECT * FROM prestb WHERE pid='$pid'");

  $output = '
  <style>
    .header { font-size: 20px; font-weight: bold; color: #00c6ff; text-align: center; }
    .sub-header { font-size: 14px; font-weight: bold; color: #333; margin-top: 20px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background-color: #00c6ff; color: white; font-weight: bold; padding: 8px; border: 1px solid #ccc; }
    td { padding: 8px; border: 1px solid #ccc; font-size: 12px; }
  </style>
  <div class="header">Apex Medical Institute</div>
  <div style="text-align:center; font-size:12px;">Patient Medical History Record</div>
  <hr color="#00c6ff">
  <h4 class="sub-header">Patient Details</h4>
  <table cellpadding="5">
    <tr>
      <td width="20%"><strong>Name:</strong></td>
      <td width="30%">'.$pat_row['fname'].' '.$pat_row['lname'].'</td>
      <td width="20%"><strong>Patient ID:</strong></td>
      <td width="30%">'.$pat_row['pid'].'</td>
    </tr>
    <tr>
      <td><strong>Email:</strong></td>
      <td>'.$pat_row['email'].'</td>
      <td><strong>Contact:</strong></td>
      <td>'.$pat_row['contact'].'</td>
    </tr>
    <tr>
      <td><strong>Gender:</strong></td>
      <td>'.$pat_row['gender'].'</td>
      <td><strong>Report Date:</strong></td>
      <td>'.date("Y-m-d").'</td>
    </tr>
  </table>
  <h4 class="sub-header">Appointment History</h4>
  <table cellpadding="5">
    <thead>
      <tr>
        <th width="20%">Date</th>
        <th width="20%">Time</th>
        <th width="30%">Doctor</th>
        <th width="30%">Status</th>
      </tr>
    </thead>
    <tbody>';
  if(mysqli_num_rows($app_query) > 0){
      while($row = mysqli_fetch_array($app_query)){
        $status = "Active";
        if($row['userStatus']==0) $status = "Cancelled by Patient";
        if($row['doctorStatus']==0) $status = "Cancelled by Doctor";
        $output .= '<tr>
          <td>'.$row['appdate'].'</td>
          <td>'.$row['apptime'].'</td>
          <td>'.$row['doctor'].'</td>
          <td>'.$status.'</td>
        </tr>';
      }
  } else {
      $output .= '<tr><td colspan="4" align="center">No appointment records found.</td></tr>';
  }
  $output .= '</tbody></table>
  <h4 class="sub-header">Prescription History</h4>
  <table cellpadding="5">
    <thead>
      <tr>
        <th width="25%">Doctor</th>
        <th width="25%">Condition</th>
        <th width="25%">Allergies</th>
        <th width="25%">Medication</th>
      </tr>
    </thead>
    <tbody>';
  if(mysqli_num_rows($pres_query) > 0){
      while($row = mysqli_fetch_array($pres_query)){
        $output .= '<tr>
          <td>'.$row['doctor'].'</td>
          <td>'.$row['disease'].'</td>
          <td>'.$row['allergy'].'</td>
          <td>'.$row['prescription'].'</td>
        </tr>';
      }
  } else {
      $output .= '<tr><td colspan="4" align="center">No prescription records found.</td></tr>';
  }
  $output .= '</tbody></table>
  <br><br>
  <div style="font-size:10px; color:#777; text-align:center;">This is an archived record generated by the Hospital Management System.</div>';
  return $output;
}

if(isset($_GET["download_record"])){
  require_once("TCPDF/tcpdf.php");
  $obj_pdf = new TCPDF('P', PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
  $obj_pdf->SetCreator(PDF_CREATOR);
  $obj_pdf->SetTitle("Patient Record - ".$_GET['pid']);
  $obj_pdf->setPrintHeader(false);
  $obj_pdf->setPrintFooter(false);
  $obj_pdf->SetMargins(15, 15, 15);
  $obj_pdf->SetAutoPageBreak(TRUE, 10);
  $obj_pdf->SetFont('helvetica', '', 10);
  $obj_pdf->AddPage();
  $content = generate_patient_history($_GET['pid']);
  $obj_pdf->writeHTML($content);
  ob_end_clean();
  $obj_pdf->Output("Patient_Record_".$_GET['pid'].".pdf", 'D'); 
  exit;
}

// 2. Logic to ADD Doctor
if(isset($_POST['docsub']))
{
  $doctor=$_POST['doctor'];
  $dpassword=$_POST['dpassword'];
  $demail=$_POST['demail'];
  $spec=$_POST['special'];
  $docFees=$_POST['docFees'];
  $query="insert into doctb(username,password,email,spec,docFees)values('$doctor','$dpassword','$demail','$spec','$docFees')";
  $result=mysqli_query($con,$query);
  if($result) { echo "<script>alert('Doctor added successfully!');</script>"; }
}

// 3. Logic to DELETE Doctor
if(isset($_POST['docsub1']))
{
  $demail=$_POST['demail'];
  $query="delete from doctb where email='$demail';";
  $result=mysqli_query($con,$query);
  if($result) { echo "<script>alert('Doctor removed successfully!');</script>"; }
  else{ echo "<script>alert('Unable to delete!');</script>"; }
}

// 4. Logic to UPDATE Doctor Fees
if(isset($_POST['docsub2']))
{
  $demail=$_POST['demail'];
  $docFees=$_POST['docFees'];
  $query="update doctb set docFees='$docFees' where email='$demail';";
  $result=mysqli_query($con,$query);
  if($result) { echo "<script>alert('Doctor Fees updated successfully!');</script>"; }
}

// 5. NEW LOGIC: DELETE PRESCRIPTION
if(isset($_GET['delete_pres']))
{
  $presID = $_GET['presID'];
  $query="delete from prestb where ID='$presID';";
  $result=mysqli_query($con,$query);
  if($result) {
      echo "<script>alert('Prescription deleted successfully!');</script>";
  }
  else{
      echo "<script>alert('Unable to delete prescription!');</script>";
  }
}

?>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="shortcut icon" type="image/x-icon" href="images/comp.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="vendor/fontawesome/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <a class="navbar-brand" href="#"><i class="fa fa-heartbeat" aria-hidden="true"></i> Apex Medical Institute </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <script >
    var check = function() {
  if (document.getElementById('dpassword').value ==
    document.getElementById('cdpassword').value) {
    document.getElementById('message').style.color = '#5dd05d';
    document.getElementById('message').innerHTML = 'Matched';
  } else {
    document.getElementById('message').style.color = '#f55252';
    document.getElementById('message').innerHTML = 'Not Matching';
  }
}

    function alphaOnly(event) {
  var key = event.keyCode;
  return ((key >= 65 && key <= 90) || key == 8 || key == 32);
};
  </script>

  <style >
    .bg-primary { background: -webkit-linear-gradient(left, #3931af, #00c6ff); }
    .navbar-nav .nav-link { color: #fff !important; opacity: 1 !important; font-weight: 600; font-size: 1.1rem; }
    .navbar-nav .nav-link:hover { color: #ffdddd !important; text-shadow: 0 0 5px rgba(255,255,255,0.5); }
    .col-md-4{ max-width:20% !important; }
    .list-group-item.active { z-index: 2; color: #fff; background-color: #342ac1; border-color: #007bff; }
    .text-primary { color: #342ac1!important; }
    #cpass { display: -webkit-box; }
    #list-app{ font-size:15px; }
    .btn-primary{ background-color: #3c50c1; border-color: #3c50c1; }
    .list-group-item { border: none; border-radius: 0.5rem !important; margin-bottom: 5px; font-weight: 600; color: #495057; transition: all 0.3s ease; }
    .list-group-item:hover { background-color: #f0f8ff; color: #00c6ff; padding-left: 25px; }
    .list-group-item.active { z-index: 2; color: #fff; background-color: #00c6ff !important; border-color: #00c6ff !important; box-shadow: 0 4px 6px rgba(0, 198, 255, 0.4); }
    .panel { border: none; border-radius: 1rem; background: #ffffff; box-shadow: 0 10px 20px rgba(0,0,0,0.05); padding: 30px 10px; margin-bottom: 30px; transition: transform 0.3s ease; }
    .panel:hover { transform: translateY(-10px); box-shadow: 0 15px 30px rgba(0, 198, 255, 0.2); }
    .fa-stack-2x { color: #00c6ff !important; }
    .fa-inverse { color: #fff; }
    .cl-effect-1 a { color: #00c6ff; font-weight: bold; font-size: 1.1rem; text-decoration: none; }
    .cl-effect-1 a:hover { color: #0099cc; text-decoration: underline; }
    h3 { color: #495057; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
    .table thead th { background: -webkit-linear-gradient(left, #3931af, #00c6ff); color: white; border: none; font-weight: 600; text-transform: uppercase; font-size: 0.95rem; padding: 15px; }
    .table thead th:first-child { border-top-left-radius: 10px; }
    .table thead th:last-child { border-top-right-radius: 10px; }
    .table tbody tr { transition: all 0.2s ease; background-color: #fff; border-bottom: 1px solid #e9ecef; }
    .table tbody tr:hover { background-color: #f0f8ff; transform: scale(1.01); box-shadow: 0 5px 15px rgba(0,0,0,0.1); z-index: 2; position: relative; }
  </style>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item">
        <a class="nav-link" href="logout1.php"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</a>
      </li>
       <li class="nav-item">
        <a class="nav-link" href="#"></a>
      </li>
    </ul>
  </div>
</nav>
  </head>
  <style type="text/css">
    button:hover{cursor:pointer;}
    #inputbtn:hover{cursor:pointer;}
  </style>
  <body style="padding-top:50px;">
   <div class="container-fluid" style="margin-top:50px;">
    <h3 style = "margin-left: 40%; padding-bottom: 20px;font-family: 'IBM Plex Sans', sans-serif;"> WELCOME Medical Secretary </h3>
    <div class="row">
  <div class="col-md-4" style="max-width:25%;margin-top: 3%;">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-dash-list" data-toggle="list" href="#list-dash" role="tab" aria-controls="home">Dashboard</a>
      <a class="list-group-item list-group-item-action" href="#list-doc" id="list-doc-list"  role="tab"    aria-controls="home" data-toggle="list">Doctor List</a>
      <a class="list-group-item list-group-item-action" href="#list-pat" id="list-pat-list"  role="tab" data-toggle="list" aria-controls="home">Patient List</a>
      <a class="list-group-item list-group-item-action" href="#list-app" id="list-app-list"  role="tab" data-toggle="list" aria-controls="home">Appointment Details</a>
      <a class="list-group-item list-group-item-action" href="#list-pres" id="list-pres-list"  role="tab" data-toggle="list" aria-controls="home">Prescription List</a>
      <a class="list-group-item list-group-item-action" href="#list-settings" id="list-adoc-list"  role="tab" data-toggle="list" aria-controls="home">Add Doctor</a>
      <a class="list-group-item list-group-item-action" href="#list-settings1" id="list-ddoc-list"  role="tab" data-toggle="list" aria-controls="home">Delete Doctor</a>
      <a class="list-group-item list-group-item-action" href="#list-settings-fees" id="list-edoc-list"  role="tab" data-toggle="list" aria-controls="home">Edit Doctor Fees</a>
      <a class="list-group-item list-group-item-action" href="#list-mes" id="list-mes-list"  role="tab" data-toggle="list" aria-controls="home">Queries</a>
      
    </div><br>
  </div>
  <div class="col-md-8" style="margin-top: 3%;">
    <div class="tab-content" id="nav-tabContent" style="width: 950px;">

      <div class="tab-pane fade show active" id="list-dash" role="tabpanel" aria-labelledby="list-dash-list">
        <div class="container-fluid container-fullw bg-white" >
              <div class="row">
               <div class="col-sm-4">
                  <div class="panel panel-white no-radius text-center">
                    <div class="panel-body">
                      <span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-users fa-stack-1x fa-inverse"></i> </span>
                      <h4 class="StepTitle" style="margin-top: 5%;">Doctor List</h4>
                      <script>
                        function clickDiv(id) {
                          document.querySelector(id).click();
                        }
                      </script> 
                      <p class="links cl-effect-1">
                        <a href="#list-doc" onclick="clickDiv('#list-doc-list')">
                          View Doctors
                        </a>
                      </p>
                    </div>
                  </div>
                </div>

                <div class="col-sm-4" style="left: -3%">
                  <div class="panel panel-white no-radius text-center">
                    <div class="panel-body" >
                      <span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-users fa-stack-1x fa-inverse"></i> </span>
                      <h4 class="StepTitle" style="margin-top: 5%;">Patient List</h4>
                      
                      <p class="cl-effect-1">
                        <a href="#list-pat" onclick="clickDiv('#list-pat-list')">
                          View Patients
                        </a>
                      </p>
                    </div>
                  </div>
                </div>
              

                <div class="col-sm-4">
                  <div class="panel panel-white no-radius text-center">
                    <div class="panel-body" >
                      <span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-paperclip fa-stack-1x fa-inverse"></i> </span>
                      <h4 class="StepTitle" style="margin-top: 5%;">Appointment Details</h4>
                    
                      <p class="cl-effect-1">
                        <a href="#list-app" onclick="clickDiv('#list-app-list')">
                          View Appointments
                        </a>
                      </p>
                    </div>
                  </div>
                </div>
                </div>

                <div class="row">
                <div class="col-sm-4" style="left: 13%;margin-top: 5%;">
                  <div class="panel panel-white no-radius text-center">
                    <div class="panel-body" >
                      <span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-list-ul fa-stack-1x fa-inverse"></i> </span>
                      <h4 class="StepTitle" style="margin-top: 5%;">Prescription List</h4>
                    
                      <p class="cl-effect-1">
                        <a href="#list-pres" onclick="clickDiv('#list-pres-list')">
                          View Prescriptions
                        </a>
                      </p>
                    </div>
                  </div>
                </div>


                <div class="col-sm-4" style="left: 18%;margin-top: 5%">
                  <div class="panel panel-white no-radius text-center">
                    <div class="panel-body" >
                      <span class="fa-stack fa-2x"> <i class="fa fa-square fa-stack-2x text-primary"></i> <i class="fa fa-plus fa-stack-1x fa-inverse"></i> </span>
                      <h4 class="StepTitle" style="margin-top: 5%;">Manage Users</h4>
                    
                      <p class="cl-effect-1">
                        <a href="#list-settings" onclick="clickDiv('#list-adoc-list')">Add Doctor</a>
                        &nbsp|
                        <a href="#list-settings1" onclick="clickDiv('#list-ddoc-list')">Delete Doctor</a>
                        &nbsp|
                        <a href="#list-settings-fees" onclick="clickDiv('#list-edoc-list')">Edit Fees</a>
                      </p>
                    </div>
                  </div>
                </div>
                </div>
              </div>
            </div>

      <div class="tab-pane fade" id="list-doc" role="tabpanel" aria-labelledby="list-home-list">
        <div class="col-md-8">
          <form class="form-group" action="doctorsearch.php" method="post">
            <div class="row">
              <div class="col-md-10">
                <input list="docSearch" type="text" name="doctor_contact" placeholder="Enter Email ID" class="form-control">
                <datalist id="docSearch">
                  <?php 
                    $query = "select email from doctb";
                    $result = mysqli_query($con,$query);
                    while($row=mysqli_fetch_array($result)){
                      echo "<option value='".$row['email']."'>";
                    }
                  ?>
                </datalist>
              </div>
              <div class="col-md-2"><input type="submit" name="doctor_search_submit" class="btn btn-primary" value="Search"></div>
            </div>
          </form>
        </div>
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Doctor Name</th>
                    <th scope="col">Specialization</th>
                    <th scope="col">Email</th>
                    <th scope="col">Password</th>
                    <th scope="col">Fees</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                    $con=mysqli_connect("localhost","root","","myhmsdb");
                    global $con;
                    $query = "select * from doctb";
                    $result = mysqli_query($con,$query);
                    while ($row = mysqli_fetch_array($result)){
                      $username = $row['username'];
                      $spec = $row['spec'];
                      $email = $row['email'];
                      $password = $row['password'];
                      $docFees = $row['docFees'];
                      
                      echo "<tr>
                        <td>$username</td>
                        <td>$spec</td>
                        <td>$email</td>
                        <td>$password</td>
                        <td>$docFees</td>
                      </tr>";
                    }

                  ?>
                </tbody>
              </table>
        <br>
      </div>
    

    <div class="tab-pane fade" id="list-pat" role="tabpanel" aria-labelledby="list-pat-list">
       <div class="col-md-8">
        <form class="form-group" action="patientsearch.php" method="post">
          <div class="row">
            <div class="col-md-10">
              <input list="patSearch" type="text" name="patient_contact" placeholder="Enter Contact" class="form-control">
              <datalist id="patSearch">
                <?php 
                  $query = "select contact from patreg";
                  $result = mysqli_query($con,$query);
                  while($row=mysqli_fetch_array($result)){
                    echo "<option value='".$row['contact']."'>";
                  }
                ?>
              </datalist>
            </div>
            <div class="col-md-2"><input type="submit" name="patient_search_submit" class="btn btn-primary" value="Search"></div>
          </div>
        </form>
      </div>
        
              <table class="table table-hover">
                <thead>
                  <tr>
                  <th scope="col">Patient ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Email</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                    $con=mysqli_connect("localhost","root","","myhmsdb");
                    global $con;
                    $query = "select * from patreg";
                    $result = mysqli_query($con,$query);
                    while ($row = mysqli_fetch_array($result)){
                      $pid = $row['pid'];
                      $fname = $row['fname'];
                      $lname = $row['lname'];
                      $gender = $row['gender'];
                      $email = $row['email'];
                      $contact = $row['contact'];
                      
                      echo "<tr>
                        <td>$pid</td>
                        <td>$fname</td>
                        <td>$lname</td>
                        <td>$gender</td>
                        <td>$email</td>
                        <td>$contact</td>
                        <td>
                          <a href='admin-panel1.php?pid=$pid&download_record=true' class='btn btn-success btn-sm'>Download History</a>
                        </td>
                      </tr>";
                    }

                  ?>
                </tbody>
              </table>
        <br>
      </div>


      <div class="tab-pane fade" id="list-pres" role="tabpanel" aria-labelledby="list-pres-list">
       <div class="col-md-8"></div>
        <div class="row">
              <table class="table table-hover">
                <thead>
                  <tr>
                  <th scope="col">Doctor</th>
                    <th scope="col">Patient ID</th>
                    <th scope="col">Appointment ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Appointment Date</th>
                    <th scope="col">Appointment Time</th>
                    <th scope="col">Disease</th>
                    <th scope="col">Allergy</th>
                    <th scope="col">Prescription</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 
                    $con=mysqli_connect("localhost","root","","myhmsdb");
                    global $con;
                    $query = "select * from prestb";
                    $result = mysqli_query($con,$query);
                    while ($row = mysqli_fetch_array($result)){
                      $doctor = $row['doctor'];
                      $pid = $row['pid'];
                      $ID = $row['ID'];
                      $fname = $row['fname'];
                      $lname = $row['lname'];
                      $appdate = $row['appdate'];
                      $apptime = $row['apptime'];
                      $disease = $row['disease'];
                      $allergy = $row['allergy'];
                      $pres = $row['prescription'];

                      echo "<tr>
                        <td>$doctor</td>
                        <td>$pid</td>
                        <td>$ID</td>
                        <td>$fname</td>
                        <td>$lname</td>
                        <td>$appdate</td>
                        <td>$apptime</td>
                        <td>$disease</td>
                        <td>$allergy</td>
                        <td>$pres</td>
                        <td>
                          <a href='admin-panel1.php?presID=$ID&delete_pres=true' 
                             onClick=\"return confirm('Are you sure you want to delete this prescription?')\"
                             class='btn btn-danger btn-sm'>Delete</a>
                        </td>
                      </tr>";
                    }

                  ?>
                </tbody>
              </table>
        <br>
      </div>
      </div>


      <div class="tab-pane fade" id="list-app" role="tabpanel" aria-labelledby="list-pat-list">
         <div class="col-md-8">
          <form class="form-group" action="appsearch.php" method="post">
            <div class="row">
              <div class="col-md-10">
                <input list="appSearch" type="text" name="app_contact" placeholder="Enter Contact" class="form-control">
                <datalist id="appSearch">
                  <?php 
                    $query = "select contact from appointmenttb";
                    $result = mysqli_query($con,$query);
                    while($row=mysqli_fetch_array($result)){
                      echo "<option value='".$row['contact']."'>";
                    }
                  ?>
                </datalist>
              </div>
              <div class="col-md-2"><input type="submit" name="app_search_submit" class="btn btn-primary" value="Search"></div>
            </div>
          </form>
        </div>
        
              <table class="table table-hover">
                <thead>
                  <tr>
                  <th scope="col">Appointment ID</th>
                  <th scope="col">Patient ID</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Email</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Doctor Name</th>
                    <th scope="col">Consultancy Fees</th>
                    <th scope="col">Appointment Date</th>
                    <th scope="col">Appointment Time</th>
                    <th scope="col">Appointment Status</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 

                    $con=mysqli_connect("localhost","root","","myhmsdb");
                    global $con;

                    $query = "select * from appointmenttb;";
                    $result = mysqli_query($con,$query);
                    while ($row = mysqli_fetch_array($result)){
                  ?>
                      <tr>
                        <td><?php echo $row['ID'];?></td>
                        <td><?php echo $row['pid'];?></td>
                        <td><?php echo $row['fname'];?></td>
                        <td><?php echo $row['lname'];?></td>
                        <td><?php echo $row['gender'];?></td>
                        <td><?php echo $row['email'];?></td>
                        <td><?php echo $row['contact'];?></td>
                        <td><?php echo $row['doctor'];?></td>
                        <td><?php echo $row['docFees'];?></td>
                        <td><?php echo $row['appdate'];?></td>
                        <td><?php echo $row['apptime'];?></td>
                        <td>
                    <?php if(($row['userStatus']==1) && ($row['doctorStatus']==1))  
                    {
                      echo "Active";
                    }
                    if(($row['userStatus']==0) && ($row['doctorStatus']==1))  
                    {
                      echo "Cancelled by Patient";
                    }

                    if(($row['userStatus']==1) && ($row['doctorStatus']==0))  
                    {
                      echo "Cancelled by Doctor";
                    }
                        ?></td>
                      </tr>
                    <?php } ?>
                </tbody>
              </table>
        <br>
      </div>

      <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">...</div>

      <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">
        <form class="form-group" method="post" action="admin-panel1.php">
          <div class="row">
                  <div class="col-md-4"><label>Doctor Name:</label></div>
                  <div class="col-md-8"><input type="text" class="form-control" name="doctor" onkeydown="return alphaOnly(event);" required></div><br><br>
                  <div class="col-md-4"><label>Specialization:</label></div>
                  <div class="col-md-8">
                   <select name="special" class="form-control" id="special" required="required">
                      <option value="head" name="spec" disabled selected>Select Specialization</option>
                      <option value="General" name="spec">General</option>
                      <option value="Cardiologist" name="spec">Cardiologist</option>
                      <option value="Neurologist" name="spec">Neurologist</option>
                      <option value="Pediatrician" name="spec">Pediatrician</option>
                    </select>
                    </div><br><br>
                  <div class="col-md-4"><label>Email ID:</label></div>
                  <div class="col-md-8"><input type="email"  class="form-control" name="demail" required></div><br><br>
                  <div class="col-md-4"><label>Password:</label></div>
                  <div class="col-md-8"><input type="password" class="form-control"  onkeyup='check();' name="dpassword" id="dpassword"  required></div><br><br>
                  <div class="col-md-4"><label>Confirm Password:</label></div>
                  <div class="col-md-8"  id='cpass'><input type="password" class="form-control" onkeyup='check();' name="cdpassword" id="cdpassword" required>&nbsp &nbsp<span id='message'></span> </div><br><br>
                   
                  
                  <div class="col-md-4"><label>Consultancy Fees:</label></div>
                  <div class="col-md-8"><input type="text" class="form-control"  name="docFees" required></div><br><br>
                </div>
          <input type="submit" name="docsub" value="Add Doctor" class="btn btn-primary">
        </form>
      </div>

      <div class="tab-pane fade" id="list-settings1" role="tabpanel" aria-labelledby="list-settings1-list">
        <form class="form-group" method="post" action="admin-panel1.php">
          <div class="row">
                  <div class="col-md-4"><label>Email ID:</label></div>
                  <div class="col-md-8">
                    <input list="delDocSearch" type="text" class="form-control" name="demail" placeholder="Type to search email..." required>
                    <datalist id="delDocSearch">
                      <?php 
                        $query = "select email from doctb";
                        $result = mysqli_query($con,$query);
                        while($row=mysqli_fetch_array($result)){
                          echo "<option value='".$row['email']."'>";
                        }
                      ?>
                    </datalist>
                  </div><br><br>
                </div>
          <input type="submit" name="docsub1" value="Delete Doctor" class="btn btn-primary" onclick="confirm('do you really want to delete?')">
        </form>
      </div>

      <div class="tab-pane fade" id="list-settings-fees" role="tabpanel" aria-labelledby="list-edoc-list">
        <form class="form-group" method="post" action="admin-panel1.php">
          <div class="row">
                  <div class="col-md-4"><label>Email ID:</label></div>
                  <div class="col-md-8">
                    <input list="docEmails" class="form-control" name="demail" placeholder="Type to search email..." required>
                    <datalist id="docEmails">
                      <?php 
                        $query = "select email from doctb";
                        $result = mysqli_query($con,$query);
                        while($row=mysqli_fetch_array($result)){
                          echo "<option value='".$row['email']."'>";
                        }
                      ?>
                    </datalist>
                  </div><br><br>
                  
                  <div class="col-md-4"><label>New Consultancy Fees:</label></div>
                  <div class="col-md-8"><input type="text" class="form-control"  name="docFees" required></div><br><br>
                </div>
          <input type="submit" name="docsub2" value="Update Fees" class="btn btn-primary">
        </form>
      </div>

       <div class="tab-pane fade" id="list-attend" role="tabpanel" aria-labelledby="list-attend-list">...</div>

       <div class="tab-pane fade" id="list-mes" role="tabpanel" aria-labelledby="list-mes-list">
         <div class="col-md-8">
          <form class="form-group" action="messearch.php" method="post">
            <div class="row">
              <div class="col-md-10">
                <input list="mesSearch" type="text" name="mes_contact" placeholder="Enter Contact" class="form-control">
                <datalist id="mesSearch">
                  <?php 
                    $query = "select contact from contact";
                    $result = mysqli_query($con,$query);
                    while($row=mysqli_fetch_array($result)){
                      echo "<option value='".$row['contact']."'>";
                    }
                  ?>
                </datalist>
              </div>
              <div class="col-md-2"><input type="submit" name="mes_search_submit" class="btn btn-primary" value="Search"></div>
            </div>
          </form>
        </div>
        
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">User Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Contact</th>
                    <th scope="col">Message</th>
                  </tr>
                </thead>
                <tbody>
                  <?php 

                    $con=mysqli_connect("localhost","root","","myhmsdb");
                    global $con;

                    $query = "select * from contact;";
                    $result = mysqli_query($con,$query);
                    while ($row = mysqli_fetch_array($result)){
                  ?>
                      <tr>
                        <td><?php echo $row['name'];?></td>
                        <td><?php echo $row['email'];?></td>
                        <td><?php echo $row['contact'];?></td>
                        <td><?php echo $row['message'];?></td>
                      </tr>
                    <?php } ?>
                </tbody>
              </table>
        <br>
      </div>

    </div>
  </div>
</div>
   </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.10.1/sweetalert2.all.min.js"></script>
  </body>
</html>